services:
    keeweb:
        build:
            dockerfile: Dockerfile
            args: # The defined arguments on the compose file are available on the Dockerfile but only before and on the FROM. After the FROM the arguments are not available:
                VERSION: 1.19.0
                BUILD_DATE: 20241216
                ALPINE_DOCKER_BUILD: "dev"
                ALPINE_VERSION: 3.21
            no_cache: true
        container_name: keeweb
        hostname: keeweb
        image: keeweb:dev                  # Dockerhub image
        restart: unless-stopped
        ports:
            - "4443:443/tcp" # host:container
        environment:
            PUID: 1000
            PGID: 1000
            TZ: "Etc/UTC"
            PORT_HTTPS: 4443
        volumes:
            - ./keeweb:/config
        depends_on:
             webdav:
                 condition: service_started
        networks:
            webdav:
    webdav:
        build:
            context: ./docker-webdav/2.4/
            dockerfile: Dockerfile
            no_cache: true
        container_name: webdav
        hostname: webdav
        image: webdav-local:latest
        restart: unless-stopped
        expose:
            - "443:443/tcp"
        volumes:
            - ./keepass:/var/lib/dav/data # volume of database
            - ./keeweb/keys/cert.crt:/cert.pem # use cert generated from keeweb
            - ./keeweb/keys/cert.key:/privkey.pem # use cert generated from keeweb
            - ./keeweb/nginx/user.passwd:/user.passwd # mount own user.password
            - ./keeweb/log/apache/error.log:/var/log/httpd/error.log
            - ./keeweb/log/apache/access.log:/var/log/httpd/access.log
        networks:
            webdav:
networks:
    webdav: